// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth/v1alpha1/attestation.proto

package eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attestation struct {
	AggregationBits      []byte           `protobuf:"bytes,1,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty"`
	Data                 *AttestationData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CustodyBitsBlocks    []byte           `protobuf:"bytes,3,opt,name=custody_bits_blocks,json=custodyBitsBlocks,proto3" json:"custody_bits_blocks,omitempty"`
	Signature            []byte           `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894c78397fc93a1, []int{0}
}

func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attestation.Unmarshal(m, b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return xxx_messageInfo_Attestation.Size(m)
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetAggregationBits() []byte {
	if m != nil {
		return m.AggregationBits
	}
	return nil
}

func (m *Attestation) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Attestation) GetCustodyBitsBlocks() []byte {
	if m != nil {
		return m.CustodyBitsBlocks
	}
	return nil
}

func (m *Attestation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type AggregateAttestationAndProof struct {
	AggregatorIndex      uint64       `protobuf:"varint,1,opt,name=aggregator_index,json=aggregatorIndex,proto3" json:"aggregator_index,omitempty"`
	Aggregate            *Attestation `protobuf:"bytes,3,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	SelectionProof       []byte       `protobuf:"bytes,2,opt,name=selection_proof,json=selectionProof,proto3" json:"selection_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AggregateAttestationAndProof) Reset()         { *m = AggregateAttestationAndProof{} }
func (m *AggregateAttestationAndProof) String() string { return proto.CompactTextString(m) }
func (*AggregateAttestationAndProof) ProtoMessage()    {}
func (*AggregateAttestationAndProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894c78397fc93a1, []int{1}
}

func (m *AggregateAttestationAndProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregateAttestationAndProof.Unmarshal(m, b)
}
func (m *AggregateAttestationAndProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregateAttestationAndProof.Marshal(b, m, deterministic)
}
func (m *AggregateAttestationAndProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregateAttestationAndProof.Merge(m, src)
}
func (m *AggregateAttestationAndProof) XXX_Size() int {
	return xxx_messageInfo_AggregateAttestationAndProof.Size(m)
}
func (m *AggregateAttestationAndProof) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregateAttestationAndProof.DiscardUnknown(m)
}

var xxx_messageInfo_AggregateAttestationAndProof proto.InternalMessageInfo

func (m *AggregateAttestationAndProof) GetAggregatorIndex() uint64 {
	if m != nil {
		return m.AggregatorIndex
	}
	return 0
}

func (m *AggregateAttestationAndProof) GetAggregate() *Attestation {
	if m != nil {
		return m.Aggregate
	}
	return nil
}

func (m *AggregateAttestationAndProof) GetSelectionProof() []byte {
	if m != nil {
		return m.SelectionProof
	}
	return nil
}

type AttestationData struct {
	Slot                 uint64      `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	CommitteeIndex       uint64      `protobuf:"varint,2,opt,name=committee_index,json=committeeIndex,proto3" json:"committee_index,omitempty"`
	BeaconBlockRoot      []byte      `protobuf:"bytes,3,opt,name=beacon_block_root,json=beaconBlockRoot,proto3" json:"beacon_block_root,omitempty"`
	Source               *Checkpoint `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Target               *Checkpoint `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	ShardHeadRoot        []byte      `protobuf:"bytes,6,opt,name=shard_head_root,json=shardHeadRoot,proto3" json:"shard_head_root,omitempty"`
	ShardTransitionRoot  []byte      `protobuf:"bytes,7,opt,name=shard_transition_root,json=shardTransitionRoot,proto3" json:"shard_transition_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AttestationData) Reset()         { *m = AttestationData{} }
func (m *AttestationData) String() string { return proto.CompactTextString(m) }
func (*AttestationData) ProtoMessage()    {}
func (*AttestationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894c78397fc93a1, []int{2}
}

func (m *AttestationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationData.Unmarshal(m, b)
}
func (m *AttestationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationData.Marshal(b, m, deterministic)
}
func (m *AttestationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationData.Merge(m, src)
}
func (m *AttestationData) XXX_Size() int {
	return xxx_messageInfo_AttestationData.Size(m)
}
func (m *AttestationData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationData.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationData proto.InternalMessageInfo

func (m *AttestationData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationData) GetCommitteeIndex() uint64 {
	if m != nil {
		return m.CommitteeIndex
	}
	return 0
}

func (m *AttestationData) GetBeaconBlockRoot() []byte {
	if m != nil {
		return m.BeaconBlockRoot
	}
	return nil
}

func (m *AttestationData) GetSource() *Checkpoint {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *AttestationData) GetTarget() *Checkpoint {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AttestationData) GetShardHeadRoot() []byte {
	if m != nil {
		return m.ShardHeadRoot
	}
	return nil
}

func (m *AttestationData) GetShardTransitionRoot() []byte {
	if m != nil {
		return m.ShardTransitionRoot
	}
	return nil
}

type Crosslink struct {
	Shard                uint64   `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	ParentRoot           []byte   `protobuf:"bytes,2,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StartEpoch           uint64   `protobuf:"varint,3,opt,name=start_epoch,json=startEpoch,proto3" json:"start_epoch,omitempty"`
	EndEpoch             uint64   `protobuf:"varint,4,opt,name=end_epoch,json=endEpoch,proto3" json:"end_epoch,omitempty"`
	DataRoot             []byte   `protobuf:"bytes,5,opt,name=data_root,json=dataRoot,proto3" json:"data_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crosslink) Reset()         { *m = Crosslink{} }
func (m *Crosslink) String() string { return proto.CompactTextString(m) }
func (*Crosslink) ProtoMessage()    {}
func (*Crosslink) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894c78397fc93a1, []int{3}
}

func (m *Crosslink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crosslink.Unmarshal(m, b)
}
func (m *Crosslink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crosslink.Marshal(b, m, deterministic)
}
func (m *Crosslink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crosslink.Merge(m, src)
}
func (m *Crosslink) XXX_Size() int {
	return xxx_messageInfo_Crosslink.Size(m)
}
func (m *Crosslink) XXX_DiscardUnknown() {
	xxx_messageInfo_Crosslink.DiscardUnknown(m)
}

var xxx_messageInfo_Crosslink proto.InternalMessageInfo

func (m *Crosslink) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *Crosslink) GetParentRoot() []byte {
	if m != nil {
		return m.ParentRoot
	}
	return nil
}

func (m *Crosslink) GetStartEpoch() uint64 {
	if m != nil {
		return m.StartEpoch
	}
	return 0
}

func (m *Crosslink) GetEndEpoch() uint64 {
	if m != nil {
		return m.EndEpoch
	}
	return 0
}

func (m *Crosslink) GetDataRoot() []byte {
	if m != nil {
		return m.DataRoot
	}
	return nil
}

type Checkpoint struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Root                 []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894c78397fc93a1, []int{4}
}

func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Checkpoint) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func init() {
	proto.RegisterType((*Attestation)(nil), "ethereum.eth.v1alpha1.Attestation")
	proto.RegisterType((*AggregateAttestationAndProof)(nil), "ethereum.eth.v1alpha1.AggregateAttestationAndProof")
	proto.RegisterType((*AttestationData)(nil), "ethereum.eth.v1alpha1.AttestationData")
	proto.RegisterType((*Crosslink)(nil), "ethereum.eth.v1alpha1.Crosslink")
	proto.RegisterType((*Checkpoint)(nil), "ethereum.eth.v1alpha1.Checkpoint")
}

func init() { proto.RegisterFile("eth/v1alpha1/attestation.proto", fileDescriptor_7894c78397fc93a1) }

var fileDescriptor_7894c78397fc93a1 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x43, 0x5a, 0x9a, 0x49, 0x69, 0xda, 0x2d, 0x95, 0x82, 0xa8, 0x68, 0xc9, 0xa1, 0x14,
	0x24, 0x1c, 0x35, 0x48, 0x48, 0x7c, 0x1c, 0x68, 0x4a, 0x24, 0xb8, 0x55, 0x16, 0x27, 0x54, 0x29,
	0xda, 0xd8, 0x83, 0xd7, 0x4a, 0xb2, 0x6b, 0xed, 0x4e, 0x10, 0xfc, 0x98, 0xfe, 0x01, 0xce, 0xfc,
	0x02, 0x8e, 0x88, 0x1f, 0x85, 0x76, 0xd6, 0x49, 0x2c, 0x54, 0x04, 0x37, 0xef, 0x7b, 0x33, 0xf3,
	0xde, 0xbc, 0xb5, 0x0d, 0x0f, 0x90, 0x54, 0xff, 0xf3, 0x99, 0x9c, 0x95, 0x4a, 0x9e, 0xf5, 0x25,
	0x11, 0x3a, 0x92, 0x54, 0x18, 0x1d, 0x97, 0xd6, 0x90, 0x11, 0x07, 0x48, 0x0a, 0x2d, 0x2e, 0xe6,
	0x31, 0x92, 0x8a, 0x97, 0x85, 0xbd, 0x1f, 0x11, 0xb4, 0xcf, 0xd7, 0xc5, 0xe2, 0x31, 0xec, 0xca,
	0x3c, 0xb7, 0x98, 0xf3, 0x71, 0x3c, 0x29, 0xc8, 0x75, 0xa3, 0xe3, 0xe8, 0x74, 0x3b, 0xe9, 0xd4,
	0xf0, 0x61, 0x41, 0x4e, 0xbc, 0x84, 0x66, 0x26, 0x49, 0x76, 0x1b, 0xc7, 0xd1, 0x69, 0x7b, 0x70,
	0x12, 0xdf, 0x28, 0x10, 0xd7, 0x86, 0xbf, 0x95, 0x24, 0x13, 0xee, 0x11, 0x31, 0xec, 0xa7, 0x0b,
	0x47, 0x26, 0xfb, 0xca, 0x12, 0xe3, 0xc9, 0xcc, 0xa4, 0x53, 0xd7, 0xbd, 0xc5, 0x4a, 0x7b, 0x15,
	0xe5, 0x55, 0x86, 0x4c, 0x88, 0x43, 0x68, 0xb9, 0x22, 0xd7, 0x92, 0x16, 0x16, 0xbb, 0x4d, 0xae,
	0x5a, 0x03, 0xbd, 0xef, 0x11, 0x1c, 0x9e, 0x57, 0xee, 0xb0, 0x26, 0x78, 0xae, 0xb3, 0x4b, 0x6b,
	0xcc, 0xa7, 0xfa, 0x56, 0xc6, 0x8e, 0x0b, 0x9d, 0xe1, 0x17, 0xde, 0xaa, 0xb9, 0xde, 0xca, 0xd8,
	0xf7, 0x1e, 0x16, 0x6f, 0xa0, 0xb5, 0x84, 0x90, 0xfd, 0xb4, 0x07, 0xbd, 0x7f, 0xaf, 0x96, 0xac,
	0x9b, 0xc4, 0x23, 0xe8, 0x38, 0x9c, 0x61, 0xca, 0x01, 0x96, 0x5e, 0x9f, 0x23, 0xda, 0x4e, 0x76,
	0x56, 0x30, 0xbb, 0xea, 0xfd, 0x6a, 0x40, 0xe7, 0x8f, 0x78, 0x84, 0x80, 0xa6, 0x9b, 0x19, 0xaa,
	0xdc, 0xf1, 0xb3, 0x1f, 0x98, 0x9a, 0xf9, 0xbc, 0x20, 0x42, 0xac, 0xcc, 0x37, 0x98, 0xde, 0x59,
	0xc1, 0xc1, 0xfb, 0x13, 0xd8, 0x9b, 0xa0, 0x4c, 0xfd, 0xbd, 0xf9, 0xd8, 0xc6, 0xd6, 0x18, 0xaa,
	0x32, 0xed, 0x04, 0x82, 0xe3, 0x4c, 0x8c, 0x21, 0xf1, 0x02, 0x36, 0x9d, 0x59, 0xd8, 0x34, 0xc4,
	0xd9, 0x1e, 0x3c, 0xfc, 0xcb, 0x92, 0x17, 0x0a, 0xd3, 0x69, 0x69, 0x0a, 0x4d, 0x49, 0xd5, 0xe0,
	0x5b, 0x49, 0xda, 0x1c, 0xa9, 0xbb, 0xf1, 0xdf, 0xad, 0xa1, 0x41, 0x9c, 0x40, 0xc7, 0x29, 0x69,
	0xb3, 0xb1, 0x42, 0x99, 0x05, 0x7f, 0x9b, 0xec, 0xef, 0x0e, 0xc3, 0xef, 0x50, 0x66, 0xec, 0x6e,
	0x00, 0x07, 0xa1, 0x8e, 0xac, 0xd4, 0xae, 0xe0, 0x28, 0xb9, 0xfa, 0x36, 0x57, 0xef, 0x33, 0xf9,
	0x61, 0xc5, 0xf9, 0x9e, 0xde, 0x75, 0x04, 0xad, 0x0b, 0x6b, 0x9c, 0x9b, 0x15, 0x7a, 0x2a, 0xee,
	0xc2, 0x06, 0x17, 0x55, 0x49, 0x86, 0x83, 0x38, 0x82, 0x76, 0x29, 0x2d, 0x6a, 0x0a, 0xd3, 0xc2,
	0xbd, 0x40, 0x80, 0x58, 0xf8, 0x08, 0xda, 0x8e, 0xa4, 0xa5, 0x31, 0x96, 0x26, 0x55, 0x1c, 0x5e,
	0x33, 0x01, 0x86, 0x46, 0x1e, 0x11, 0xf7, 0xa1, 0x85, 0x3a, 0xab, 0xe8, 0x26, 0xd3, 0x5b, 0xa8,
	0xb3, 0x15, 0xe9, 0x5f, 0xef, 0x30, 0x7c, 0x83, 0x87, 0x6f, 0x79, 0x80, 0xfd, 0x3d, 0x07, 0x58,
	0x27, 0xe2, 0xfd, 0x85, 0x19, 0x95, 0x3f, 0x3e, 0xf8, 0xeb, 0xaf, 0x19, 0xe3, 0xe7, 0xe1, 0x75,
	0x04, 0xf7, 0x8c, 0xcd, 0x6f, 0x0e, 0x79, 0xb8, 0x5b, 0x7b, 0x83, 0x2e, 0xfd, 0x97, 0x7e, 0x19,
	0x7d, 0x7c, 0x9d, 0x17, 0xa4, 0x16, 0x93, 0x38, 0x35, 0xf3, 0x3e, 0xa1, 0x45, 0x9d, 0x62, 0xaa,
	0x64, 0xa1, 0xfb, 0xcb, 0x11, 0xb2, 0x2c, 0xdc, 0xd3, 0x52, 0x49, 0x87, 0x67, 0xfd, 0xfa, 0x7f,
	0xe3, 0x15, 0x92, 0xfa, 0xd6, 0x38, 0x18, 0x2d, 0x95, 0x46, 0x35, 0xa5, 0x9f, 0x6b, 0xfc, 0x6a,
	0x44, 0xea, 0x6a, 0x89, 0x4f, 0x36, 0xf9, 0x07, 0xf3, 0xec, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x9d, 0x02, 0x6a, 0x79, 0x82, 0x04, 0x00, 0x00,
}
