// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth/v1alpha1/beacon_block.proto

package eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BeaconBlock struct {
	Slot                 uint64           `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ParentRoot           []byte           `protobuf:"bytes,2,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot            []byte           `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Body                 *BeaconBlockBody `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BeaconBlock) Reset()         { *m = BeaconBlock{} }
func (m *BeaconBlock) String() string { return proto.CompactTextString(m) }
func (*BeaconBlock) ProtoMessage()    {}
func (*BeaconBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{0}
}

func (m *BeaconBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlock.Unmarshal(m, b)
}
func (m *BeaconBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlock.Marshal(b, m, deterministic)
}
func (m *BeaconBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlock.Merge(m, src)
}
func (m *BeaconBlock) XXX_Size() int {
	return xxx_messageInfo_BeaconBlock.Size(m)
}
func (m *BeaconBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlock.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlock proto.InternalMessageInfo

func (m *BeaconBlock) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *BeaconBlock) GetParentRoot() []byte {
	if m != nil {
		return m.ParentRoot
	}
	return nil
}

func (m *BeaconBlock) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BeaconBlock) GetBody() *BeaconBlockBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type SignedBeaconBlock struct {
	Block                *BeaconBlock `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Signature            []byte       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignedBeaconBlock) Reset()         { *m = SignedBeaconBlock{} }
func (m *SignedBeaconBlock) String() string { return proto.CompactTextString(m) }
func (*SignedBeaconBlock) ProtoMessage()    {}
func (*SignedBeaconBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{1}
}

func (m *SignedBeaconBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBeaconBlock.Unmarshal(m, b)
}
func (m *SignedBeaconBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBeaconBlock.Marshal(b, m, deterministic)
}
func (m *SignedBeaconBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBeaconBlock.Merge(m, src)
}
func (m *SignedBeaconBlock) XXX_Size() int {
	return xxx_messageInfo_SignedBeaconBlock.Size(m)
}
func (m *SignedBeaconBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBeaconBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBeaconBlock proto.InternalMessageInfo

func (m *SignedBeaconBlock) GetBlock() *BeaconBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *SignedBeaconBlock) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BeaconBlockBody struct {
	RandaoReveal              []byte                 `protobuf:"bytes,1,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty"`
	Eth1Data                  *Eth1Data              `protobuf:"bytes,2,opt,name=eth1_data,json=eth1Data,proto3" json:"eth1_data,omitempty"`
	Graffiti                  []byte                 `protobuf:"bytes,3,opt,name=graffiti,proto3" json:"graffiti,omitempty"`
	ProposerSlashings         []*ProposerSlashing    `protobuf:"bytes,4,rep,name=proposer_slashings,json=proposerSlashings,proto3" json:"proposer_slashings,omitempty"`
	AttesterSlashings         []*AttesterSlashing    `protobuf:"bytes,5,rep,name=attester_slashings,json=attesterSlashings,proto3" json:"attester_slashings,omitempty"`
	Attestations              []*Attestation         `protobuf:"bytes,6,rep,name=attestations,proto3" json:"attestations,omitempty"`
	Deposits                  []*Deposit             `protobuf:"bytes,7,rep,name=deposits,proto3" json:"deposits,omitempty"`
	VoluntaryExits            []*SignedVoluntaryExit `protobuf:"bytes,8,rep,name=voluntary_exits,json=voluntaryExits,proto3" json:"voluntary_exits,omitempty"`
	CustodySlashings          [][]byte               `protobuf:"bytes,9,rep,name=custody_slashings,json=custodySlashings,proto3" json:"custody_slashings,omitempty"`
	CustodyKeyReveals         [][]byte               `protobuf:"bytes,10,rep,name=custody_key_reveals,json=custodyKeyReveals,proto3" json:"custody_key_reveals,omitempty"`
	EarlyDerivedSecretReveals [][]byte               `protobuf:"bytes,11,rep,name=early_derived_secret_reveals,json=earlyDerivedSecretReveals,proto3" json:"early_derived_secret_reveals,omitempty"`
	ShardTransitions          []*ShardTransition     `protobuf:"bytes,12,rep,name=shard_transitions,json=shardTransitions,proto3" json:"shard_transitions,omitempty"`
	LightClientSignatureBits  [][]byte               `protobuf:"bytes,13,rep,name=light_client_signature_bits,json=lightClientSignatureBits,proto3" json:"light_client_signature_bits,omitempty"`
	LightClientSignature      []byte                 `protobuf:"bytes,14,opt,name=light_client_signature,json=lightClientSignature,proto3" json:"light_client_signature,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}               `json:"-"`
	XXX_unrecognized          []byte                 `json:"-"`
	XXX_sizecache             int32                  `json:"-"`
}

func (m *BeaconBlockBody) Reset()         { *m = BeaconBlockBody{} }
func (m *BeaconBlockBody) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockBody) ProtoMessage()    {}
func (*BeaconBlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{2}
}

func (m *BeaconBlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockBody.Unmarshal(m, b)
}
func (m *BeaconBlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockBody.Marshal(b, m, deterministic)
}
func (m *BeaconBlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockBody.Merge(m, src)
}
func (m *BeaconBlockBody) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockBody.Size(m)
}
func (m *BeaconBlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockBody proto.InternalMessageInfo

func (m *BeaconBlockBody) GetRandaoReveal() []byte {
	if m != nil {
		return m.RandaoReveal
	}
	return nil
}

func (m *BeaconBlockBody) GetEth1Data() *Eth1Data {
	if m != nil {
		return m.Eth1Data
	}
	return nil
}

func (m *BeaconBlockBody) GetGraffiti() []byte {
	if m != nil {
		return m.Graffiti
	}
	return nil
}

func (m *BeaconBlockBody) GetProposerSlashings() []*ProposerSlashing {
	if m != nil {
		return m.ProposerSlashings
	}
	return nil
}

func (m *BeaconBlockBody) GetAttesterSlashings() []*AttesterSlashing {
	if m != nil {
		return m.AttesterSlashings
	}
	return nil
}

func (m *BeaconBlockBody) GetAttestations() []*Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func (m *BeaconBlockBody) GetDeposits() []*Deposit {
	if m != nil {
		return m.Deposits
	}
	return nil
}

func (m *BeaconBlockBody) GetVoluntaryExits() []*SignedVoluntaryExit {
	if m != nil {
		return m.VoluntaryExits
	}
	return nil
}

func (m *BeaconBlockBody) GetCustodySlashings() [][]byte {
	if m != nil {
		return m.CustodySlashings
	}
	return nil
}

func (m *BeaconBlockBody) GetCustodyKeyReveals() [][]byte {
	if m != nil {
		return m.CustodyKeyReveals
	}
	return nil
}

func (m *BeaconBlockBody) GetEarlyDerivedSecretReveals() [][]byte {
	if m != nil {
		return m.EarlyDerivedSecretReveals
	}
	return nil
}

func (m *BeaconBlockBody) GetShardTransitions() []*ShardTransition {
	if m != nil {
		return m.ShardTransitions
	}
	return nil
}

func (m *BeaconBlockBody) GetLightClientSignatureBits() [][]byte {
	if m != nil {
		return m.LightClientSignatureBits
	}
	return nil
}

func (m *BeaconBlockBody) GetLightClientSignature() []byte {
	if m != nil {
		return m.LightClientSignature
	}
	return nil
}

type ProposerSlashing struct {
	ProposerIndex        uint64                   `protobuf:"varint,1,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
	Header_1             *SignedBeaconBlockHeader `protobuf:"bytes,2,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header_2             *SignedBeaconBlockHeader `protobuf:"bytes,3,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ProposerSlashing) Reset()         { *m = ProposerSlashing{} }
func (m *ProposerSlashing) String() string { return proto.CompactTextString(m) }
func (*ProposerSlashing) ProtoMessage()    {}
func (*ProposerSlashing) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{3}
}

func (m *ProposerSlashing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposerSlashing.Unmarshal(m, b)
}
func (m *ProposerSlashing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposerSlashing.Marshal(b, m, deterministic)
}
func (m *ProposerSlashing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposerSlashing.Merge(m, src)
}
func (m *ProposerSlashing) XXX_Size() int {
	return xxx_messageInfo_ProposerSlashing.Size(m)
}
func (m *ProposerSlashing) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposerSlashing.DiscardUnknown(m)
}

var xxx_messageInfo_ProposerSlashing proto.InternalMessageInfo

func (m *ProposerSlashing) GetProposerIndex() uint64 {
	if m != nil {
		return m.ProposerIndex
	}
	return 0
}

func (m *ProposerSlashing) GetHeader_1() *SignedBeaconBlockHeader {
	if m != nil {
		return m.Header_1
	}
	return nil
}

func (m *ProposerSlashing) GetHeader_2() *SignedBeaconBlockHeader {
	if m != nil {
		return m.Header_2
	}
	return nil
}

type AttesterSlashing struct {
	Attestation_1        *IndexedAttestation `protobuf:"bytes,1,opt,name=attestation_1,json=attestation1,proto3" json:"attestation_1,omitempty"`
	Attestation_2        *IndexedAttestation `protobuf:"bytes,2,opt,name=attestation_2,json=attestation2,proto3" json:"attestation_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AttesterSlashing) Reset()         { *m = AttesterSlashing{} }
func (m *AttesterSlashing) String() string { return proto.CompactTextString(m) }
func (*AttesterSlashing) ProtoMessage()    {}
func (*AttesterSlashing) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{4}
}

func (m *AttesterSlashing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttesterSlashing.Unmarshal(m, b)
}
func (m *AttesterSlashing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttesterSlashing.Marshal(b, m, deterministic)
}
func (m *AttesterSlashing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttesterSlashing.Merge(m, src)
}
func (m *AttesterSlashing) XXX_Size() int {
	return xxx_messageInfo_AttesterSlashing.Size(m)
}
func (m *AttesterSlashing) XXX_DiscardUnknown() {
	xxx_messageInfo_AttesterSlashing.DiscardUnknown(m)
}

var xxx_messageInfo_AttesterSlashing proto.InternalMessageInfo

func (m *AttesterSlashing) GetAttestation_1() *IndexedAttestation {
	if m != nil {
		return m.Attestation_1
	}
	return nil
}

func (m *AttesterSlashing) GetAttestation_2() *IndexedAttestation {
	if m != nil {
		return m.Attestation_2
	}
	return nil
}

type Deposit struct {
	Proof                [][]byte      `protobuf:"bytes,1,rep,name=proof,proto3" json:"proof,omitempty"`
	Data                 *Deposit_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Deposit) Reset()         { *m = Deposit{} }
func (m *Deposit) String() string { return proto.CompactTextString(m) }
func (*Deposit) ProtoMessage()    {}
func (*Deposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{5}
}

func (m *Deposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deposit.Unmarshal(m, b)
}
func (m *Deposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deposit.Marshal(b, m, deterministic)
}
func (m *Deposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deposit.Merge(m, src)
}
func (m *Deposit) XXX_Size() int {
	return xxx_messageInfo_Deposit.Size(m)
}
func (m *Deposit) XXX_DiscardUnknown() {
	xxx_messageInfo_Deposit.DiscardUnknown(m)
}

var xxx_messageInfo_Deposit proto.InternalMessageInfo

func (m *Deposit) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *Deposit) GetData() *Deposit_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Deposit_Data struct {
	PublicKey             []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WithdrawalCredentials []byte   `protobuf:"bytes,2,opt,name=withdrawal_credentials,json=withdrawalCredentials,proto3" json:"withdrawal_credentials,omitempty"`
	Amount                uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Signature             []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Deposit_Data) Reset()         { *m = Deposit_Data{} }
func (m *Deposit_Data) String() string { return proto.CompactTextString(m) }
func (*Deposit_Data) ProtoMessage()    {}
func (*Deposit_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{5, 0}
}

func (m *Deposit_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deposit_Data.Unmarshal(m, b)
}
func (m *Deposit_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deposit_Data.Marshal(b, m, deterministic)
}
func (m *Deposit_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deposit_Data.Merge(m, src)
}
func (m *Deposit_Data) XXX_Size() int {
	return xxx_messageInfo_Deposit_Data.Size(m)
}
func (m *Deposit_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Deposit_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Deposit_Data proto.InternalMessageInfo

func (m *Deposit_Data) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Deposit_Data) GetWithdrawalCredentials() []byte {
	if m != nil {
		return m.WithdrawalCredentials
	}
	return nil
}

func (m *Deposit_Data) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Deposit_Data) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type VoluntaryExit struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ValidatorIndex       uint64   `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoluntaryExit) Reset()         { *m = VoluntaryExit{} }
func (m *VoluntaryExit) String() string { return proto.CompactTextString(m) }
func (*VoluntaryExit) ProtoMessage()    {}
func (*VoluntaryExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{6}
}

func (m *VoluntaryExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoluntaryExit.Unmarshal(m, b)
}
func (m *VoluntaryExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoluntaryExit.Marshal(b, m, deterministic)
}
func (m *VoluntaryExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoluntaryExit.Merge(m, src)
}
func (m *VoluntaryExit) XXX_Size() int {
	return xxx_messageInfo_VoluntaryExit.Size(m)
}
func (m *VoluntaryExit) XXX_DiscardUnknown() {
	xxx_messageInfo_VoluntaryExit.DiscardUnknown(m)
}

var xxx_messageInfo_VoluntaryExit proto.InternalMessageInfo

func (m *VoluntaryExit) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *VoluntaryExit) GetValidatorIndex() uint64 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

type SignedVoluntaryExit struct {
	Exit                 *VoluntaryExit `protobuf:"bytes,1,opt,name=exit,proto3" json:"exit,omitempty"`
	Signature            []byte         `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignedVoluntaryExit) Reset()         { *m = SignedVoluntaryExit{} }
func (m *SignedVoluntaryExit) String() string { return proto.CompactTextString(m) }
func (*SignedVoluntaryExit) ProtoMessage()    {}
func (*SignedVoluntaryExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{7}
}

func (m *SignedVoluntaryExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedVoluntaryExit.Unmarshal(m, b)
}
func (m *SignedVoluntaryExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedVoluntaryExit.Marshal(b, m, deterministic)
}
func (m *SignedVoluntaryExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedVoluntaryExit.Merge(m, src)
}
func (m *SignedVoluntaryExit) XXX_Size() int {
	return xxx_messageInfo_SignedVoluntaryExit.Size(m)
}
func (m *SignedVoluntaryExit) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedVoluntaryExit.DiscardUnknown(m)
}

var xxx_messageInfo_SignedVoluntaryExit proto.InternalMessageInfo

func (m *SignedVoluntaryExit) GetExit() *VoluntaryExit {
	if m != nil {
		return m.Exit
	}
	return nil
}

func (m *SignedVoluntaryExit) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Eth1Data struct {
	DepositRoot          []byte   `protobuf:"bytes,1,opt,name=deposit_root,json=depositRoot,proto3" json:"deposit_root,omitempty"`
	DepositCount         uint64   `protobuf:"varint,2,opt,name=deposit_count,json=depositCount,proto3" json:"deposit_count,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Eth1Data) Reset()         { *m = Eth1Data{} }
func (m *Eth1Data) String() string { return proto.CompactTextString(m) }
func (*Eth1Data) ProtoMessage()    {}
func (*Eth1Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{8}
}

func (m *Eth1Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Eth1Data.Unmarshal(m, b)
}
func (m *Eth1Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Eth1Data.Marshal(b, m, deterministic)
}
func (m *Eth1Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Eth1Data.Merge(m, src)
}
func (m *Eth1Data) XXX_Size() int {
	return xxx_messageInfo_Eth1Data.Size(m)
}
func (m *Eth1Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Eth1Data.DiscardUnknown(m)
}

var xxx_messageInfo_Eth1Data proto.InternalMessageInfo

func (m *Eth1Data) GetDepositRoot() []byte {
	if m != nil {
		return m.DepositRoot
	}
	return nil
}

func (m *Eth1Data) GetDepositCount() uint64 {
	if m != nil {
		return m.DepositCount
	}
	return 0
}

func (m *Eth1Data) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type BeaconBlockHeader struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ParentRoot           []byte   `protobuf:"bytes,2,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot            []byte   `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	BodyRoot             []byte   `protobuf:"bytes,4,opt,name=body_root,json=bodyRoot,proto3" json:"body_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockHeader) Reset()         { *m = BeaconBlockHeader{} }
func (m *BeaconBlockHeader) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockHeader) ProtoMessage()    {}
func (*BeaconBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{9}
}

func (m *BeaconBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockHeader.Unmarshal(m, b)
}
func (m *BeaconBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockHeader.Marshal(b, m, deterministic)
}
func (m *BeaconBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockHeader.Merge(m, src)
}
func (m *BeaconBlockHeader) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockHeader.Size(m)
}
func (m *BeaconBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockHeader proto.InternalMessageInfo

func (m *BeaconBlockHeader) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *BeaconBlockHeader) GetParentRoot() []byte {
	if m != nil {
		return m.ParentRoot
	}
	return nil
}

func (m *BeaconBlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BeaconBlockHeader) GetBodyRoot() []byte {
	if m != nil {
		return m.BodyRoot
	}
	return nil
}

type SignedBeaconBlockHeader struct {
	Header               *BeaconBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SignedBeaconBlockHeader) Reset()         { *m = SignedBeaconBlockHeader{} }
func (m *SignedBeaconBlockHeader) String() string { return proto.CompactTextString(m) }
func (*SignedBeaconBlockHeader) ProtoMessage()    {}
func (*SignedBeaconBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{10}
}

func (m *SignedBeaconBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBeaconBlockHeader.Unmarshal(m, b)
}
func (m *SignedBeaconBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBeaconBlockHeader.Marshal(b, m, deterministic)
}
func (m *SignedBeaconBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBeaconBlockHeader.Merge(m, src)
}
func (m *SignedBeaconBlockHeader) XXX_Size() int {
	return xxx_messageInfo_SignedBeaconBlockHeader.Size(m)
}
func (m *SignedBeaconBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBeaconBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBeaconBlockHeader proto.InternalMessageInfo

func (m *SignedBeaconBlockHeader) GetHeader() *BeaconBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedBeaconBlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type IndexedAttestation struct {
	AttestingIndices     []uint64         `protobuf:"varint,1,rep,packed,name=attesting_indices,json=attestingIndices,proto3" json:"attesting_indices,omitempty"`
	Data                 *AttestationData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IndexedAttestation) Reset()         { *m = IndexedAttestation{} }
func (m *IndexedAttestation) String() string { return proto.CompactTextString(m) }
func (*IndexedAttestation) ProtoMessage()    {}
func (*IndexedAttestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6abbd9d98bd3d11a, []int{11}
}

func (m *IndexedAttestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexedAttestation.Unmarshal(m, b)
}
func (m *IndexedAttestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexedAttestation.Marshal(b, m, deterministic)
}
func (m *IndexedAttestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexedAttestation.Merge(m, src)
}
func (m *IndexedAttestation) XXX_Size() int {
	return xxx_messageInfo_IndexedAttestation.Size(m)
}
func (m *IndexedAttestation) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexedAttestation.DiscardUnknown(m)
}

var xxx_messageInfo_IndexedAttestation proto.InternalMessageInfo

func (m *IndexedAttestation) GetAttestingIndices() []uint64 {
	if m != nil {
		return m.AttestingIndices
	}
	return nil
}

func (m *IndexedAttestation) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*BeaconBlock)(nil), "ethereum.eth.v1alpha1.BeaconBlock")
	proto.RegisterType((*SignedBeaconBlock)(nil), "ethereum.eth.v1alpha1.SignedBeaconBlock")
	proto.RegisterType((*BeaconBlockBody)(nil), "ethereum.eth.v1alpha1.BeaconBlockBody")
	proto.RegisterType((*ProposerSlashing)(nil), "ethereum.eth.v1alpha1.ProposerSlashing")
	proto.RegisterType((*AttesterSlashing)(nil), "ethereum.eth.v1alpha1.AttesterSlashing")
	proto.RegisterType((*Deposit)(nil), "ethereum.eth.v1alpha1.Deposit")
	proto.RegisterType((*Deposit_Data)(nil), "ethereum.eth.v1alpha1.Deposit.Data")
	proto.RegisterType((*VoluntaryExit)(nil), "ethereum.eth.v1alpha1.VoluntaryExit")
	proto.RegisterType((*SignedVoluntaryExit)(nil), "ethereum.eth.v1alpha1.SignedVoluntaryExit")
	proto.RegisterType((*Eth1Data)(nil), "ethereum.eth.v1alpha1.Eth1Data")
	proto.RegisterType((*BeaconBlockHeader)(nil), "ethereum.eth.v1alpha1.BeaconBlockHeader")
	proto.RegisterType((*SignedBeaconBlockHeader)(nil), "ethereum.eth.v1alpha1.SignedBeaconBlockHeader")
	proto.RegisterType((*IndexedAttestation)(nil), "ethereum.eth.v1alpha1.IndexedAttestation")
}

func init() { proto.RegisterFile("eth/v1alpha1/beacon_block.proto", fileDescriptor_6abbd9d98bd3d11a) }

var fileDescriptor_6abbd9d98bd3d11a = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x51, 0x6f, 0xdb, 0x36,
	0x10, 0x86, 0x12, 0x25, 0xb1, 0xcf, 0x76, 0xe2, 0xb0, 0x4d, 0xa6, 0xa6, 0x4d, 0x93, 0x29, 0x5b,
	0xeb, 0x6d, 0x98, 0x03, 0x7b, 0x1b, 0x56, 0x74, 0x1d, 0xb6, 0x39, 0xc9, 0xd0, 0xa0, 0x40, 0x11,
	0xc8, 0x43, 0x1f, 0x86, 0x02, 0x02, 0x2d, 0x31, 0x16, 0x11, 0x45, 0xd4, 0x48, 0xda, 0x8d, 0x1f,
	0xf6, 0x30, 0x60, 0xbf, 0x60, 0xef, 0xfd, 0x03, 0x7b, 0xdc, 0xcf, 0xd8, 0xcb, 0x7e, 0xc9, 0xfe,
	0xc3, 0x20, 0x92, 0xb2, 0x65, 0xd7, 0x8e, 0x81, 0x02, 0x7b, 0x13, 0xef, 0xee, 0xfb, 0x48, 0x9e,
	0xee, 0xbb, 0x23, 0x1c, 0x10, 0x19, 0x1d, 0x0f, 0x5b, 0x38, 0x4e, 0x23, 0xdc, 0x3a, 0xee, 0x11,
	0x1c, 0xb0, 0xc4, 0xef, 0xc5, 0x2c, 0xb8, 0x6a, 0xa6, 0x9c, 0x49, 0x86, 0x76, 0x88, 0x8c, 0x08,
	0x27, 0x83, 0xeb, 0x26, 0x91, 0x51, 0x33, 0x8f, 0xdc, 0x7b, 0x38, 0x85, 0xc3, 0x52, 0x12, 0x21,
	0xb1, 0xa4, 0x2c, 0xd1, 0xb0, 0x3d, 0x67, 0xca, 0x2f, 0x22, 0xcc, 0x43, 0xed, 0x71, 0xdf, 0x5a,
	0x50, 0xe9, 0xa8, 0x7d, 0x3a, 0xd9, 0x36, 0x08, 0x81, 0x2d, 0x62, 0x26, 0x1d, 0xeb, 0xd0, 0x6a,
	0xd8, 0x9e, 0xfa, 0x46, 0x07, 0x50, 0x49, 0x31, 0x27, 0x89, 0xf4, 0x39, 0x63, 0xd2, 0x59, 0x39,
	0xb4, 0x1a, 0x55, 0x0f, 0xb4, 0xc9, 0x63, 0x4c, 0xa2, 0x7d, 0x80, 0x6c, 0x3f, 0xa2, 0xfd, 0xab,
	0xca, 0x5f, 0x56, 0x16, 0xe5, 0x7e, 0x0a, 0x76, 0x8f, 0x85, 0x23, 0xc7, 0x3e, 0xb4, 0x1a, 0x95,
	0xf6, 0xa3, 0xe6, 0xdc, 0x3b, 0x34, 0x0b, 0xa7, 0xe8, 0xb0, 0x70, 0xe4, 0x29, 0x8c, 0x7b, 0x05,
	0xdb, 0x5d, 0xda, 0x4f, 0x48, 0x58, 0x3c, 0xe4, 0x13, 0x58, 0x53, 0x49, 0x51, 0xa7, 0xac, 0xb4,
	0xdd, 0xe5, 0x8c, 0x9e, 0x06, 0xa0, 0x07, 0x50, 0x16, 0xb4, 0x9f, 0x60, 0x39, 0xe0, 0xc4, 0x5c,
	0x64, 0x62, 0x70, 0x7f, 0xdb, 0x80, 0xad, 0x99, 0x63, 0xa0, 0x23, 0xa8, 0x71, 0x9c, 0x84, 0x98,
	0xf9, 0x9c, 0x0c, 0x09, 0x8e, 0xd5, 0x9e, 0x55, 0xaf, 0xaa, 0x8d, 0x9e, 0xb2, 0xa1, 0x67, 0x50,
	0x26, 0x32, 0x6a, 0xf9, 0x21, 0x96, 0x58, 0xd1, 0x56, 0xda, 0x07, 0x0b, 0x0e, 0x75, 0x26, 0xa3,
	0xd6, 0x29, 0x96, 0xd8, 0x2b, 0x11, 0xf3, 0x85, 0xf6, 0xa0, 0xd4, 0xe7, 0xf8, 0xf2, 0x92, 0x4a,
	0x6a, 0x92, 0x37, 0x5e, 0xa3, 0x57, 0x80, 0x52, 0xce, 0x52, 0x26, 0x08, 0xf7, 0x45, 0x8c, 0x45,
	0x44, 0x93, 0xbe, 0x70, 0xec, 0xc3, 0xd5, 0x46, 0xa5, 0xfd, 0x78, 0xc1, 0x16, 0x17, 0x06, 0xd0,
	0x35, 0xf1, 0xde, 0x76, 0x3a, 0x63, 0x11, 0x19, 0xaf, 0x2e, 0x93, 0x29, 0xde, 0xb5, 0x5b, 0x79,
	0x7f, 0x30, 0x80, 0x09, 0x2f, 0x9e, 0xb1, 0x08, 0xf4, 0x23, 0x54, 0x0b, 0xe5, 0x27, 0x9c, 0x75,
	0xc5, 0xe8, 0xde, 0xca, 0xa8, 0x42, 0xbd, 0x29, 0x1c, 0x7a, 0x0a, 0xa5, 0x90, 0xa4, 0x4c, 0x50,
	0x29, 0x9c, 0x0d, 0xc5, 0xf1, 0x70, 0x01, 0xc7, 0xa9, 0x0e, 0xf3, 0xc6, 0xf1, 0xa8, 0x0b, 0x5b,
	0x43, 0x16, 0x0f, 0x12, 0x89, 0xf9, 0xc8, 0x27, 0x37, 0x19, 0x45, 0x49, 0x51, 0x7c, 0xba, 0x80,
	0x42, 0x57, 0xd8, 0xab, 0x1c, 0x73, 0x76, 0x43, 0xa5, 0xb7, 0x39, 0x2c, 0x2e, 0x05, 0xfa, 0x0c,
	0xb6, 0x83, 0x81, 0x90, 0x2c, 0x1c, 0x15, 0xf2, 0x55, 0x3e, 0x5c, 0x6d, 0x54, 0xbd, 0xba, 0x71,
	0x4c, 0xb2, 0xd0, 0x84, 0x3b, 0x79, 0xf0, 0x15, 0x19, 0x99, 0xca, 0x11, 0x0e, 0xa8, 0xf0, 0x9c,
	0xe7, 0x05, 0x19, 0xe9, 0xf2, 0x11, 0xe8, 0x3b, 0x78, 0x40, 0x30, 0x8f, 0x47, 0x7e, 0x48, 0x38,
	0x1d, 0x92, 0xd0, 0x17, 0x24, 0xe0, 0x44, 0x8e, 0x81, 0x15, 0x05, 0xbc, 0xa7, 0x62, 0x4e, 0x75,
	0x48, 0x57, 0x45, 0xe4, 0x04, 0x5d, 0xd8, 0x56, 0xaa, 0xf6, 0x25, 0xc7, 0x89, 0xa0, 0x3a, 0xf7,
	0x55, 0x75, 0xe9, 0x45, 0x7a, 0xeb, 0x66, 0xf1, 0x3f, 0x8d, 0xc3, 0xbd, 0xba, 0x98, 0x36, 0x08,
	0xf4, 0x2d, 0xdc, 0x8f, 0x69, 0x3f, 0x92, 0x7e, 0x10, 0xd3, 0x4c, 0xfd, 0x63, 0xa1, 0xf8, 0xbd,
	0x2c, 0xa7, 0x35, 0x75, 0x28, 0x47, 0x85, 0x9c, 0xa8, 0x88, 0x6e, 0x1e, 0xd0, 0xc9, 0x32, 0xf6,
	0x25, 0xec, 0xce, 0x87, 0x3b, 0x9b, 0xaa, 0xc8, 0xef, 0xce, 0x43, 0xba, 0xff, 0x58, 0x50, 0x9f,
	0x2d, 0x60, 0xf4, 0x31, 0x6c, 0x8e, 0x55, 0x40, 0x93, 0x90, 0xdc, 0x98, 0xfe, 0x54, 0xcb, 0xad,
	0xe7, 0x99, 0x11, 0x9d, 0x43, 0x29, 0x22, 0x38, 0x24, 0xdc, 0x6f, 0x19, 0x15, 0x36, 0x6f, 0xfd,
	0xe3, 0x05, 0xad, 0x3f, 0x57, 0x38, 0x6f, 0x43, 0xe3, 0x5b, 0x05, 0xaa, 0xb6, 0xd2, 0xe4, 0x7b,
	0x53, 0xb5, 0xdd, 0xbf, 0x2c, 0xa8, 0xcf, 0x4a, 0x07, 0xbd, 0x84, 0x5a, 0xa1, 0xde, 0xfd, 0x96,
	0x69, 0x65, 0x9f, 0x2c, 0xd8, 0x44, 0xdd, 0x8f, 0x84, 0x8b, 0xf4, 0xd2, 0x9a, 0xe5, 0x6b, 0x9b,
	0xfb, 0xbf, 0x27, 0x5f, 0xdb, 0xfd, 0xd7, 0x82, 0x0d, 0xa3, 0x2c, 0x74, 0x17, 0xd6, 0x52, 0xce,
	0xd8, 0xa5, 0x63, 0xa9, 0x3f, 0xae, 0x17, 0xe8, 0x6b, 0xb0, 0x0b, 0xed, 0xee, 0xe8, 0x76, 0x75,
	0x36, 0x55, 0xcb, 0x53, 0x80, 0xbd, 0x3f, 0x2c, 0xb0, 0x55, 0xdf, 0xdb, 0x07, 0x48, 0x07, 0xbd,
	0x98, 0x06, 0x99, 0x48, 0x4c, 0x5f, 0x2d, 0x6b, 0xcb, 0x0b, 0x32, 0x42, 0x5f, 0xc1, 0xee, 0x1b,
	0x2a, 0xa3, 0x90, 0xe3, 0x37, 0x38, 0xf6, 0x03, 0x4e, 0x42, 0x92, 0x48, 0x9a, 0xc9, 0x41, 0x37,
	0xee, 0x9d, 0x89, 0xf7, 0x64, 0xe2, 0x44, 0xbb, 0xb0, 0x8e, 0xaf, 0xd9, 0x20, 0xd1, 0x83, 0xc8,
	0xf6, 0xcc, 0x6a, 0xba, 0xf5, 0xdb, 0xb3, 0xad, 0xff, 0x25, 0xd4, 0xa6, 0xf4, 0x9f, 0x5d, 0x9a,
	0xa4, 0x2c, 0x88, 0x4c, 0xa5, 0xe9, 0x05, 0x7a, 0x0c, 0x5b, 0x43, 0x1c, 0xd3, 0x10, 0x4b, 0x96,
	0x57, 0xe2, 0x8a, 0xf2, 0x6f, 0x8e, 0xcd, 0x2a, 0xb5, 0xee, 0x35, 0xdc, 0x99, 0xd3, 0x55, 0xd0,
	0x13, 0xb0, 0xb3, 0x86, 0x64, 0xfe, 0xf6, 0x47, 0x0b, 0x92, 0x36, 0xdd, 0x89, 0x14, 0x62, 0xc9,
	0xe4, 0xfa, 0x05, 0x4a, 0xf9, 0x60, 0x41, 0x1f, 0x42, 0xd5, 0xb4, 0x42, 0x3d, 0x8f, 0x75, 0x62,
	0x2b, 0xc6, 0xa6, 0x26, 0xf2, 0x11, 0xd4, 0xf2, 0x90, 0x40, 0xa5, 0x4a, 0x5f, 0x22, 0xc7, 0x9d,
	0xa8, 0x84, 0xed, 0x03, 0xa8, 0xa1, 0xe9, 0x47, 0x58, 0x44, 0xf9, 0x54, 0x57, 0x96, 0xe7, 0x58,
	0x44, 0xee, 0xef, 0x16, 0x6c, 0xbf, 0x53, 0xf5, 0xff, 0xcb, 0xfb, 0xe1, 0x3e, 0x94, 0xb3, 0xb7,
	0x80, 0xf6, 0xea, 0x3f, 0x57, 0xca, 0x0c, 0x99, 0xd3, 0x1d, 0xc1, 0x07, 0x0b, 0x14, 0x88, 0xbe,
	0x87, 0x75, 0xad, 0x41, 0x93, 0xee, 0xc6, 0xf2, 0x77, 0x82, 0xd1, 0xae, 0xc1, 0x2d, 0x49, 0xfa,
	0xaf, 0x80, 0xde, 0xd5, 0x51, 0x36, 0x28, 0xb4, 0x92, 0x68, 0xd2, 0xcf, 0x4a, 0x84, 0x06, 0x44,
	0x28, 0xe5, 0xd8, 0x5e, 0x7d, 0xec, 0x38, 0xd7, 0xf6, 0xec, 0x69, 0x54, 0x10, 0xd1, 0xa3, 0xe5,
	0x63, 0x72, 0xa2, 0xa3, 0xce, 0x5b, 0x0b, 0xee, 0x31, 0xde, 0x9f, 0x8f, 0xe9, 0xd4, 0x0b, 0xb7,
	0xba, 0xc8, 0x9e, 0x7a, 0x17, 0xd6, 0xcf, 0xcf, 0xfa, 0x54, 0x46, 0x83, 0x5e, 0x33, 0x60, 0xd7,
	0xc7, 0x92, 0x70, 0x92, 0x04, 0x24, 0x88, 0x30, 0x4d, 0x8e, 0x73, 0x0a, 0x9c, 0x52, 0xf1, 0x79,
	0x1a, 0x61, 0x41, 0x5a, 0xc7, 0xc5, 0x27, 0xe3, 0x37, 0x44, 0x46, 0x7f, 0xae, 0xec, 0x9c, 0xe5,
	0x3b, 0x9d, 0x15, 0x76, 0xfa, 0x7b, 0x62, 0x7f, 0x7d, 0x26, 0xa3, 0xd7, 0xb9, 0xbd, 0xb7, 0xae,
	0x5e, 0x98, 0x5f, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x8d, 0xf6, 0xe5, 0xd5, 0x0a, 0x00,
	0x00,
}
