// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth/v1alpha1/shard.proto

package eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShardState struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Gasprice             uint64   `protobuf:"varint,2,opt,name=gasprice,proto3" json:"gasprice,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	LatestBlockRoot      []byte   `protobuf:"bytes,4,opt,name=latest_block_root,json=latestBlockRoot,proto3" json:"latest_block_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardState) Reset()         { *m = ShardState{} }
func (m *ShardState) String() string { return proto.CompactTextString(m) }
func (*ShardState) ProtoMessage()    {}
func (*ShardState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{0}
}

func (m *ShardState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardState.Unmarshal(m, b)
}
func (m *ShardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardState.Marshal(b, m, deterministic)
}
func (m *ShardState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardState.Merge(m, src)
}
func (m *ShardState) XXX_Size() int {
	return xxx_messageInfo_ShardState.Size(m)
}
func (m *ShardState) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardState.DiscardUnknown(m)
}

var xxx_messageInfo_ShardState proto.InternalMessageInfo

func (m *ShardState) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ShardState) GetGasprice() uint64 {
	if m != nil {
		return m.Gasprice
	}
	return 0
}

func (m *ShardState) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ShardState) GetLatestBlockRoot() []byte {
	if m != nil {
		return m.LatestBlockRoot
	}
	return nil
}

type ShardTransition struct {
	StartSlot            uint64   `protobuf:"varint,1,opt,name=start_slot,json=startSlot,proto3" json:"start_slot,omitempty"`
	ShardBlockLengths    []uint64 `protobuf:"varint,2,rep,packed,name=shard_block_lengths,json=shardBlockLengths,proto3" json:"shard_block_lengths,omitempty"`
	ShardDataRoots       [][]byte `protobuf:"bytes,3,rep,name=shard_data_roots,json=shardDataRoots,proto3" json:"shard_data_roots,omitempty"`
	ShardStates          [][]byte `protobuf:"bytes,4,rep,name=shard_states,json=shardStates,proto3" json:"shard_states,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardTransition) Reset()         { *m = ShardTransition{} }
func (m *ShardTransition) String() string { return proto.CompactTextString(m) }
func (*ShardTransition) ProtoMessage()    {}
func (*ShardTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{1}
}

func (m *ShardTransition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardTransition.Unmarshal(m, b)
}
func (m *ShardTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardTransition.Marshal(b, m, deterministic)
}
func (m *ShardTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardTransition.Merge(m, src)
}
func (m *ShardTransition) XXX_Size() int {
	return xxx_messageInfo_ShardTransition.Size(m)
}
func (m *ShardTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardTransition.DiscardUnknown(m)
}

var xxx_messageInfo_ShardTransition proto.InternalMessageInfo

func (m *ShardTransition) GetStartSlot() uint64 {
	if m != nil {
		return m.StartSlot
	}
	return 0
}

func (m *ShardTransition) GetShardBlockLengths() []uint64 {
	if m != nil {
		return m.ShardBlockLengths
	}
	return nil
}

func (m *ShardTransition) GetShardDataRoots() [][]byte {
	if m != nil {
		return m.ShardDataRoots
	}
	return nil
}

func (m *ShardTransition) GetShardStates() [][]byte {
	if m != nil {
		return m.ShardStates
	}
	return nil
}

func (m *ShardTransition) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ShardState)(nil), "ethereum.eth.v1alpha1.ShardState")
	proto.RegisterType((*ShardTransition)(nil), "ethereum.eth.v1alpha1.ShardTransition")
}

func init() { proto.RegisterFile("eth/v1alpha1/shard.proto", fileDescriptor_5d9da510e571288b) }

var fileDescriptor_5d9da510e571288b = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x4b, 0xeb, 0x40,
	0x10, 0xc7, 0x49, 0x93, 0xf7, 0x78, 0xdd, 0x57, 0x5e, 0xdb, 0x7d, 0x14, 0x56, 0x51, 0x88, 0x3d,
	0x05, 0xc1, 0x84, 0xe2, 0x51, 0x2f, 0x16, 0x7b, 0xf3, 0x50, 0x52, 0x4f, 0x52, 0x28, 0xd3, 0x74,
	0xc9, 0x06, 0xd3, 0x6c, 0xd8, 0x99, 0x7a, 0xf2, 0xab, 0xf8, 0x05, 0xfc, 0x28, 0xfa, 0xa5, 0x64,
	0x37, 0xa6, 0xed, 0xc1, 0xdb, 0xe6, 0x3f, 0x3f, 0x66, 0xfe, 0xff, 0x99, 0x30, 0x21, 0x49, 0x25,
	0x2f, 0x13, 0x28, 0x6b, 0x05, 0x93, 0x04, 0x15, 0x98, 0x4d, 0x5c, 0x1b, 0x4d, 0x9a, 0x8f, 0x24,
	0x29, 0x69, 0xe4, 0x6e, 0x1b, 0x4b, 0x52, 0x71, 0x8b, 0x8c, 0x5f, 0x19, 0x5b, 0x58, 0x6a, 0x41,
	0x40, 0x92, 0x73, 0x16, 0x60, 0xa9, 0x49, 0x78, 0xa1, 0x17, 0x05, 0xa9, 0x7b, 0xf3, 0x53, 0xf6,
	0x27, 0x07, 0xac, 0x4d, 0x91, 0x49, 0xd1, 0x71, 0xfa, 0xfe, 0xdb, 0xf2, 0x1b, 0x20, 0x10, 0x7e,
	0xe8, 0x45, 0xbd, 0xd4, 0xbd, 0xf9, 0x25, 0x1b, 0x96, 0x40, 0x12, 0x69, 0xb5, 0x2e, 0x75, 0xf6,
	0xbc, 0x32, 0x5a, 0x93, 0x08, 0x1c, 0xd0, 0x6f, 0x0a, 0x53, 0xab, 0xa7, 0x5a, 0xd3, 0xf8, 0xd3,
	0x63, 0x7d, 0x37, 0xfe, 0xd1, 0x40, 0x85, 0x05, 0x15, 0xba, 0xe2, 0xe7, 0x8c, 0x21, 0x81, 0xa1,
	0xd5, 0x91, 0x93, 0xae, 0x53, 0x16, 0xd6, 0x4e, 0xcc, 0xfe, 0xbb, 0x58, 0xdf, 0xdd, 0x4b, 0x59,
	0xe5, 0xa4, 0x50, 0x74, 0x42, 0x3f, 0x0a, 0xd2, 0xa1, 0x2b, 0xb9, 0xfe, 0x0f, 0x4d, 0x81, 0x47,
	0x6c, 0xd0, 0xf0, 0xd6, 0x9c, 0x33, 0x83, 0xc2, 0x0f, 0xfd, 0xa8, 0x97, 0xfe, 0x73, 0xfa, 0x3d,
	0x10, 0x58, 0x2f, 0xc8, 0x2f, 0x58, 0xaf, 0x21, 0xd1, 0xee, 0x02, 0x45, 0xe0, 0xa8, 0xbf, 0xb8,
	0x5f, 0x0f, 0xf2, 0x33, 0xd6, 0xc5, 0x22, 0xaf, 0x80, 0x76, 0x46, 0x8a, 0x5f, 0x2e, 0xd3, 0x41,
	0x98, 0xbe, 0x79, 0xec, 0x44, 0x9b, 0x3c, 0xfe, 0x71, 0xd3, 0xd3, 0xc1, 0x1d, 0xd9, 0xf0, 0x60,
	0x43, 0xce, 0xed, 0x49, 0xe6, 0xde, 0xd3, 0x6d, 0x5e, 0x90, 0xda, 0xad, 0xe3, 0x4c, 0x6f, 0x13,
	0x92, 0x46, 0x56, 0x99, 0xcc, 0x14, 0x14, 0x55, 0xd2, 0xb6, 0x80, 0xba, 0xc0, 0xab, 0x5a, 0x01,
	0xca, 0x49, 0x72, 0x7c, 0xda, 0x1b, 0x49, 0xea, 0xbd, 0x33, 0x9a, 0xb5, 0x93, 0x66, 0x47, 0x93,
	0x3e, 0x0e, 0xfa, 0x72, 0x46, 0x6a, 0xd9, 0xea, 0xeb, 0xdf, 0xee, 0x4f, 0xb8, 0xfe, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x62, 0x55, 0x04, 0x53, 0x25, 0x02, 0x00, 0x00,
}
